/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PlatformRouteRouteImport } from './routes/_platform/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthAuthRouteImport } from './routes/_auth/auth'
import { Route as PlatformSettingsTeamRouteImport } from './routes/_platform/settings.team'
import { Route as PlatformSettingsLimitsRouteImport } from './routes/_platform/settings.limits'
import { Route as PlatformSettingsGeneralRouteImport } from './routes/_platform/settings.general'
import { Route as PlatformDeveloperPermissionsRouteImport } from './routes/_platform/developer.permissions'
import { Route as PlatformDeveloperObservabilityRouteImport } from './routes/_platform/developer.observability'
import { Route as PlatformDeveloperApiKeysRouteImport } from './routes/_platform/developer.api-keys'
import { Route as PlatformOrchestraOverviewRouteImport } from './routes/_platform/_orchestra/overview'
import { Route as PlatformOrchestraAuditLogsRouteImport } from './routes/_platform/_orchestra/audit-logs'
import { Route as PlatformOrchestraAnalyticsRouteImport } from './routes/_platform/_orchestra/analytics'

const PlatformRouteRoute = PlatformRouteRouteImport.update({
  id: '/_platform',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAuthRoute = AuthAuthRouteImport.update({
  id: '/_auth/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformSettingsTeamRoute = PlatformSettingsTeamRouteImport.update({
  id: '/settings/team',
  path: '/settings/team',
  getParentRoute: () => PlatformRouteRoute,
} as any)
const PlatformSettingsLimitsRoute = PlatformSettingsLimitsRouteImport.update({
  id: '/settings/limits',
  path: '/settings/limits',
  getParentRoute: () => PlatformRouteRoute,
} as any)
const PlatformSettingsGeneralRoute = PlatformSettingsGeneralRouteImport.update({
  id: '/settings/general',
  path: '/settings/general',
  getParentRoute: () => PlatformRouteRoute,
} as any)
const PlatformDeveloperPermissionsRoute =
  PlatformDeveloperPermissionsRouteImport.update({
    id: '/developer/permissions',
    path: '/developer/permissions',
    getParentRoute: () => PlatformRouteRoute,
  } as any)
const PlatformDeveloperObservabilityRoute =
  PlatformDeveloperObservabilityRouteImport.update({
    id: '/developer/observability',
    path: '/developer/observability',
    getParentRoute: () => PlatformRouteRoute,
  } as any)
const PlatformDeveloperApiKeysRoute =
  PlatformDeveloperApiKeysRouteImport.update({
    id: '/developer/api-keys',
    path: '/developer/api-keys',
    getParentRoute: () => PlatformRouteRoute,
  } as any)
const PlatformOrchestraOverviewRoute =
  PlatformOrchestraOverviewRouteImport.update({
    id: '/_orchestra/overview',
    path: '/overview',
    getParentRoute: () => PlatformRouteRoute,
  } as any)
const PlatformOrchestraAuditLogsRoute =
  PlatformOrchestraAuditLogsRouteImport.update({
    id: '/_orchestra/audit-logs',
    path: '/audit-logs',
    getParentRoute: () => PlatformRouteRoute,
  } as any)
const PlatformOrchestraAnalyticsRoute =
  PlatformOrchestraAnalyticsRouteImport.update({
    id: '/_orchestra/analytics',
    path: '/analytics',
    getParentRoute: () => PlatformRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthAuthRoute
  '/analytics': typeof PlatformOrchestraAnalyticsRoute
  '/audit-logs': typeof PlatformOrchestraAuditLogsRoute
  '/overview': typeof PlatformOrchestraOverviewRoute
  '/developer/api-keys': typeof PlatformDeveloperApiKeysRoute
  '/developer/observability': typeof PlatformDeveloperObservabilityRoute
  '/developer/permissions': typeof PlatformDeveloperPermissionsRoute
  '/settings/general': typeof PlatformSettingsGeneralRoute
  '/settings/limits': typeof PlatformSettingsLimitsRoute
  '/settings/team': typeof PlatformSettingsTeamRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthAuthRoute
  '/analytics': typeof PlatformOrchestraAnalyticsRoute
  '/audit-logs': typeof PlatformOrchestraAuditLogsRoute
  '/overview': typeof PlatformOrchestraOverviewRoute
  '/developer/api-keys': typeof PlatformDeveloperApiKeysRoute
  '/developer/observability': typeof PlatformDeveloperObservabilityRoute
  '/developer/permissions': typeof PlatformDeveloperPermissionsRoute
  '/settings/general': typeof PlatformSettingsGeneralRoute
  '/settings/limits': typeof PlatformSettingsLimitsRoute
  '/settings/team': typeof PlatformSettingsTeamRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_platform': typeof PlatformRouteRouteWithChildren
  '/_auth/auth': typeof AuthAuthRoute
  '/_platform/_orchestra/analytics': typeof PlatformOrchestraAnalyticsRoute
  '/_platform/_orchestra/audit-logs': typeof PlatformOrchestraAuditLogsRoute
  '/_platform/_orchestra/overview': typeof PlatformOrchestraOverviewRoute
  '/_platform/developer/api-keys': typeof PlatformDeveloperApiKeysRoute
  '/_platform/developer/observability': typeof PlatformDeveloperObservabilityRoute
  '/_platform/developer/permissions': typeof PlatformDeveloperPermissionsRoute
  '/_platform/settings/general': typeof PlatformSettingsGeneralRoute
  '/_platform/settings/limits': typeof PlatformSettingsLimitsRoute
  '/_platform/settings/team': typeof PlatformSettingsTeamRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/analytics'
    | '/audit-logs'
    | '/overview'
    | '/developer/api-keys'
    | '/developer/observability'
    | '/developer/permissions'
    | '/settings/general'
    | '/settings/limits'
    | '/settings/team'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/analytics'
    | '/audit-logs'
    | '/overview'
    | '/developer/api-keys'
    | '/developer/observability'
    | '/developer/permissions'
    | '/settings/general'
    | '/settings/limits'
    | '/settings/team'
  id:
    | '__root__'
    | '/'
    | '/_platform'
    | '/_auth/auth'
    | '/_platform/_orchestra/analytics'
    | '/_platform/_orchestra/audit-logs'
    | '/_platform/_orchestra/overview'
    | '/_platform/developer/api-keys'
    | '/_platform/developer/observability'
    | '/_platform/developer/permissions'
    | '/_platform/settings/general'
    | '/_platform/settings/limits'
    | '/_platform/settings/team'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PlatformRouteRoute: typeof PlatformRouteRouteWithChildren
  AuthAuthRoute: typeof AuthAuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_platform': {
      id: '/_platform'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PlatformRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/auth': {
      id: '/_auth/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_platform/settings/team': {
      id: '/_platform/settings/team'
      path: '/settings/team'
      fullPath: '/settings/team'
      preLoaderRoute: typeof PlatformSettingsTeamRouteImport
      parentRoute: typeof PlatformRouteRoute
    }
    '/_platform/settings/limits': {
      id: '/_platform/settings/limits'
      path: '/settings/limits'
      fullPath: '/settings/limits'
      preLoaderRoute: typeof PlatformSettingsLimitsRouteImport
      parentRoute: typeof PlatformRouteRoute
    }
    '/_platform/settings/general': {
      id: '/_platform/settings/general'
      path: '/settings/general'
      fullPath: '/settings/general'
      preLoaderRoute: typeof PlatformSettingsGeneralRouteImport
      parentRoute: typeof PlatformRouteRoute
    }
    '/_platform/developer/permissions': {
      id: '/_platform/developer/permissions'
      path: '/developer/permissions'
      fullPath: '/developer/permissions'
      preLoaderRoute: typeof PlatformDeveloperPermissionsRouteImport
      parentRoute: typeof PlatformRouteRoute
    }
    '/_platform/developer/observability': {
      id: '/_platform/developer/observability'
      path: '/developer/observability'
      fullPath: '/developer/observability'
      preLoaderRoute: typeof PlatformDeveloperObservabilityRouteImport
      parentRoute: typeof PlatformRouteRoute
    }
    '/_platform/developer/api-keys': {
      id: '/_platform/developer/api-keys'
      path: '/developer/api-keys'
      fullPath: '/developer/api-keys'
      preLoaderRoute: typeof PlatformDeveloperApiKeysRouteImport
      parentRoute: typeof PlatformRouteRoute
    }
    '/_platform/_orchestra/overview': {
      id: '/_platform/_orchestra/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof PlatformOrchestraOverviewRouteImport
      parentRoute: typeof PlatformRouteRoute
    }
    '/_platform/_orchestra/audit-logs': {
      id: '/_platform/_orchestra/audit-logs'
      path: '/audit-logs'
      fullPath: '/audit-logs'
      preLoaderRoute: typeof PlatformOrchestraAuditLogsRouteImport
      parentRoute: typeof PlatformRouteRoute
    }
    '/_platform/_orchestra/analytics': {
      id: '/_platform/_orchestra/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof PlatformOrchestraAnalyticsRouteImport
      parentRoute: typeof PlatformRouteRoute
    }
  }
}

interface PlatformRouteRouteChildren {
  PlatformOrchestraAnalyticsRoute: typeof PlatformOrchestraAnalyticsRoute
  PlatformOrchestraAuditLogsRoute: typeof PlatformOrchestraAuditLogsRoute
  PlatformOrchestraOverviewRoute: typeof PlatformOrchestraOverviewRoute
  PlatformDeveloperApiKeysRoute: typeof PlatformDeveloperApiKeysRoute
  PlatformDeveloperObservabilityRoute: typeof PlatformDeveloperObservabilityRoute
  PlatformDeveloperPermissionsRoute: typeof PlatformDeveloperPermissionsRoute
  PlatformSettingsGeneralRoute: typeof PlatformSettingsGeneralRoute
  PlatformSettingsLimitsRoute: typeof PlatformSettingsLimitsRoute
  PlatformSettingsTeamRoute: typeof PlatformSettingsTeamRoute
}

const PlatformRouteRouteChildren: PlatformRouteRouteChildren = {
  PlatformOrchestraAnalyticsRoute: PlatformOrchestraAnalyticsRoute,
  PlatformOrchestraAuditLogsRoute: PlatformOrchestraAuditLogsRoute,
  PlatformOrchestraOverviewRoute: PlatformOrchestraOverviewRoute,
  PlatformDeveloperApiKeysRoute: PlatformDeveloperApiKeysRoute,
  PlatformDeveloperObservabilityRoute: PlatformDeveloperObservabilityRoute,
  PlatformDeveloperPermissionsRoute: PlatformDeveloperPermissionsRoute,
  PlatformSettingsGeneralRoute: PlatformSettingsGeneralRoute,
  PlatformSettingsLimitsRoute: PlatformSettingsLimitsRoute,
  PlatformSettingsTeamRoute: PlatformSettingsTeamRoute,
}

const PlatformRouteRouteWithChildren = PlatformRouteRoute._addFileChildren(
  PlatformRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PlatformRouteRoute: PlatformRouteRouteWithChildren,
  AuthAuthRoute: AuthAuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
