/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as BillingRouteImport } from './routes/billing'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SellIndexRouteImport } from './routes/sell.index'
import { Route as BuyIndexRouteImport } from './routes/buy.index'
import { Route as SellAssetRouteImport } from './routes/sell.$asset'
import { Route as BuyAssetRouteImport } from './routes/buy.$asset'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingRoute = BillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SellIndexRoute = SellIndexRouteImport.update({
  id: '/sell/',
  path: '/sell/',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyIndexRoute = BuyIndexRouteImport.update({
  id: '/buy/',
  path: '/buy/',
  getParentRoute: () => rootRouteImport,
} as any)
const SellAssetRoute = SellAssetRouteImport.update({
  id: '/sell/$asset',
  path: '/sell/$asset',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyAssetRoute = BuyAssetRouteImport.update({
  id: '/buy/$asset',
  path: '/buy/$asset',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/billing': typeof BillingRoute
  '/onboarding': typeof OnboardingRoute
  '/buy/$asset': typeof BuyAssetRoute
  '/sell/$asset': typeof SellAssetRoute
  '/buy/': typeof BuyIndexRoute
  '/sell/': typeof SellIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/billing': typeof BillingRoute
  '/onboarding': typeof OnboardingRoute
  '/buy/$asset': typeof BuyAssetRoute
  '/sell/$asset': typeof SellAssetRoute
  '/buy': typeof BuyIndexRoute
  '/sell': typeof SellIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/billing': typeof BillingRoute
  '/onboarding': typeof OnboardingRoute
  '/buy/$asset': typeof BuyAssetRoute
  '/sell/$asset': typeof SellAssetRoute
  '/buy/': typeof BuyIndexRoute
  '/sell/': typeof SellIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/billing'
    | '/onboarding'
    | '/buy/$asset'
    | '/sell/$asset'
    | '/buy/'
    | '/sell/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/billing'
    | '/onboarding'
    | '/buy/$asset'
    | '/sell/$asset'
    | '/buy'
    | '/sell'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/billing'
    | '/onboarding'
    | '/buy/$asset'
    | '/sell/$asset'
    | '/buy/'
    | '/sell/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BillingRoute: typeof BillingRoute
  OnboardingRoute: typeof OnboardingRoute
  BuyAssetRoute: typeof BuyAssetRoute
  SellAssetRoute: typeof SellAssetRoute
  BuyIndexRoute: typeof BuyIndexRoute
  SellIndexRoute: typeof SellIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing': {
      id: '/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sell/': {
      id: '/sell/'
      path: '/sell'
      fullPath: '/sell/'
      preLoaderRoute: typeof SellIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buy/': {
      id: '/buy/'
      path: '/buy'
      fullPath: '/buy/'
      preLoaderRoute: typeof BuyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sell/$asset': {
      id: '/sell/$asset'
      path: '/sell/$asset'
      fullPath: '/sell/$asset'
      preLoaderRoute: typeof SellAssetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buy/$asset': {
      id: '/buy/$asset'
      path: '/buy/$asset'
      fullPath: '/buy/$asset'
      preLoaderRoute: typeof BuyAssetRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BillingRoute: BillingRoute,
  OnboardingRoute: OnboardingRoute,
  BuyAssetRoute: BuyAssetRoute,
  SellAssetRoute: SellAssetRoute,
  BuyIndexRoute: BuyIndexRoute,
  SellIndexRoute: SellIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
