/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RIndexRouteImport } from './routes/r/index'
import { Route as RRefRouteImport } from './routes/r/$ref'

const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RIndexRoute = RIndexRouteImport.update({
  id: '/r/',
  path: '/r/',
  getParentRoute: () => rootRouteImport,
} as any)
const RRefRoute = RRefRouteImport.update({
  id: '/r/$ref',
  path: '/r/$ref',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/verify': typeof VerifyRoute
  '/r/$ref': typeof RRefRoute
  '/r/': typeof RIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/verify': typeof VerifyRoute
  '/r/$ref': typeof RRefRoute
  '/r': typeof RIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/verify': typeof VerifyRoute
  '/r/$ref': typeof RRefRoute
  '/r/': typeof RIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/verify' | '/r/$ref' | '/r/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/verify' | '/r/$ref' | '/r'
  id: '__root__' | '/' | '/verify' | '/r/$ref' | '/r/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  VerifyRoute: typeof VerifyRoute
  RRefRoute: typeof RRefRoute
  RIndexRoute: typeof RIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/': {
      id: '/r/'
      path: '/r'
      fullPath: '/r/'
      preLoaderRoute: typeof RIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$ref': {
      id: '/r/$ref'
      path: '/r/$ref'
      fullPath: '/r/$ref'
      preLoaderRoute: typeof RRefRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  VerifyRoute: VerifyRoute,
  RRefRoute: RRefRoute,
  RIndexRoute: RIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
