# fly.toml app configuration file generated for baggit on 2026-07-07T15:41:14+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'baggit'
primary_region = 'lhr'

[build]
  dockerfile = './Dockerfile'

[deploy]
	release_command = "./packages/api/app-db-migrations.sh"

[processes]
  api = 'bun run start:packages:api'
  auth = 'bun run start:packages:auth'
  caddy = 'caddy run --config /etc/caddy/Caddyfile'
  worker-email = 'bun run start:worker:email'

[[service]]
  auto_stop_machines = 'suspend'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['api']

# Public service — attached ONLY to the caddy process group
[[services]]
    processes    = ["caddy"]
    protocol     = "tcp"
    internal_port = 8080

    [[services.ports]]
        port        = 80
        handlers    = ["http"]
        force_https = true

    [[services.ports]]
        port        = 443
        handlers    = ["tls", "http"]

[[vm]]
  memory = '2gb'
  cpus = 2
  cpu_kind = 'shared'
  persist_rootfs = "never"
  memory_mb = 2048
  processes = ['api']

[[vm]]
  memory = '512mb'
  cpus = 1
  memory_mb = 512
  processes = ['auth']
