/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SpaRouteImport } from './routes/spa'
import { Route as MainRouteRouteImport } from './routes/_main/route'
import { Route as MainIndexRouteImport } from './routes/_main/index'
import { Route as MicroRampRouteImport } from './routes/micro/ramp'
import { Route as ApiReferralRouteImport } from './routes/api/referral'
import { Route as MainSellRouteImport } from './routes/_main/sell'
import { Route as MainBuyRouteImport } from './routes/_main/buy'
import { Route as walletWalletRouteImport } from './routes/(wallet)/wallet'

const SpaRoute = SpaRouteImport.update({
  id: '/spa',
  path: '/spa',
  getParentRoute: () => rootRouteImport,
} as any)
const MainRouteRoute = MainRouteRouteImport.update({
  id: '/_main',
  getParentRoute: () => rootRouteImport,
} as any)
const MainIndexRoute = MainIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainRouteRoute,
} as any)
const MicroRampRoute = MicroRampRouteImport.update({
  id: '/micro/ramp',
  path: '/micro/ramp',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReferralRoute = ApiReferralRouteImport.update({
  id: '/api/referral',
  path: '/api/referral',
  getParentRoute: () => rootRouteImport,
} as any)
const MainSellRoute = MainSellRouteImport.update({
  id: '/sell',
  path: '/sell',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainBuyRoute = MainBuyRouteImport.update({
  id: '/buy',
  path: '/buy',
  getParentRoute: () => MainRouteRoute,
} as any)
const walletWalletRoute = walletWalletRouteImport.update({
  id: '/(wallet)/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof MainIndexRoute
  '/spa': typeof SpaRoute
  '/wallet': typeof walletWalletRoute
  '/buy': typeof MainBuyRoute
  '/sell': typeof MainSellRoute
  '/api/referral': typeof ApiReferralRoute
  '/micro/ramp': typeof MicroRampRoute
}
export interface FileRoutesByTo {
  '/spa': typeof SpaRoute
  '/wallet': typeof walletWalletRoute
  '/buy': typeof MainBuyRoute
  '/sell': typeof MainSellRoute
  '/api/referral': typeof ApiReferralRoute
  '/micro/ramp': typeof MicroRampRoute
  '/': typeof MainIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_main': typeof MainRouteRouteWithChildren
  '/spa': typeof SpaRoute
  '/(wallet)/wallet': typeof walletWalletRoute
  '/_main/buy': typeof MainBuyRoute
  '/_main/sell': typeof MainSellRoute
  '/api/referral': typeof ApiReferralRoute
  '/micro/ramp': typeof MicroRampRoute
  '/_main/': typeof MainIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/spa'
    | '/wallet'
    | '/buy'
    | '/sell'
    | '/api/referral'
    | '/micro/ramp'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/spa'
    | '/wallet'
    | '/buy'
    | '/sell'
    | '/api/referral'
    | '/micro/ramp'
    | '/'
  id:
    | '__root__'
    | '/_main'
    | '/spa'
    | '/(wallet)/wallet'
    | '/_main/buy'
    | '/_main/sell'
    | '/api/referral'
    | '/micro/ramp'
    | '/_main/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  MainRouteRoute: typeof MainRouteRouteWithChildren
  SpaRoute: typeof SpaRoute
  walletWalletRoute: typeof walletWalletRoute
  ApiReferralRoute: typeof ApiReferralRoute
  MicroRampRoute: typeof MicroRampRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/spa': {
      id: '/spa'
      path: '/spa'
      fullPath: '/spa'
      preLoaderRoute: typeof SpaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main': {
      id: '/_main'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MainRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/': {
      id: '/_main/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MainIndexRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/micro/ramp': {
      id: '/micro/ramp'
      path: '/micro/ramp'
      fullPath: '/micro/ramp'
      preLoaderRoute: typeof MicroRampRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/referral': {
      id: '/api/referral'
      path: '/api/referral'
      fullPath: '/api/referral'
      preLoaderRoute: typeof ApiReferralRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/sell': {
      id: '/_main/sell'
      path: '/sell'
      fullPath: '/sell'
      preLoaderRoute: typeof MainSellRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/buy': {
      id: '/_main/buy'
      path: '/buy'
      fullPath: '/buy'
      preLoaderRoute: typeof MainBuyRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/(wallet)/wallet': {
      id: '/(wallet)/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof walletWalletRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface MainRouteRouteChildren {
  MainBuyRoute: typeof MainBuyRoute
  MainSellRoute: typeof MainSellRoute
  MainIndexRoute: typeof MainIndexRoute
}

const MainRouteRouteChildren: MainRouteRouteChildren = {
  MainBuyRoute: MainBuyRoute,
  MainSellRoute: MainSellRoute,
  MainIndexRoute: MainIndexRoute,
}

const MainRouteRouteWithChildren = MainRouteRoute._addFileChildren(
  MainRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  MainRouteRoute: MainRouteRouteWithChildren,
  SpaRoute: SpaRoute,
  walletWalletRoute: walletWalletRoute,
  ApiReferralRoute: ApiReferralRoute,
  MicroRampRoute: MicroRampRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
