/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PaymentRouteImport } from './routes/payment'
import { Route as OverviewRouteImport } from './routes/overview'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RRegistryDotjsonRouteImport } from './routes/r.registry[.]json'
import { Route as RNameDotjsonRouteImport } from './routes/r.$name[.]json'

const PaymentRoute = PaymentRouteImport.update({
  id: '/payment',
  path: '/payment',
  getParentRoute: () => rootRouteImport,
} as any)
const OverviewRoute = OverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RRegistryDotjsonRoute = RRegistryDotjsonRouteImport.update({
  id: '/r/registry.json',
  path: '/r/registry.json',
  getParentRoute: () => rootRouteImport,
} as any)
const RNameDotjsonRoute = RNameDotjsonRouteImport.update({
  id: '/r/$name.json',
  path: '/r/$name.json',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/overview': typeof OverviewRoute
  '/payment': typeof PaymentRoute
  '/r/$name.json': typeof RNameDotjsonRoute
  '/r/registry.json': typeof RRegistryDotjsonRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/overview': typeof OverviewRoute
  '/payment': typeof PaymentRoute
  '/r/$name.json': typeof RNameDotjsonRoute
  '/r/registry.json': typeof RRegistryDotjsonRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/overview': typeof OverviewRoute
  '/payment': typeof PaymentRoute
  '/r/$name.json': typeof RNameDotjsonRoute
  '/r/registry.json': typeof RRegistryDotjsonRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/overview'
    | '/payment'
    | '/r/$name.json'
    | '/r/registry.json'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/overview'
    | '/payment'
    | '/r/$name.json'
    | '/r/registry.json'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/overview'
    | '/payment'
    | '/r/$name.json'
    | '/r/registry.json'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  OverviewRoute: typeof OverviewRoute
  PaymentRoute: typeof PaymentRoute
  RNameDotjsonRoute: typeof RNameDotjsonRoute
  RRegistryDotjsonRoute: typeof RRegistryDotjsonRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/payment': {
      id: '/payment'
      path: '/payment'
      fullPath: '/payment'
      preLoaderRoute: typeof PaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/overview': {
      id: '/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof OverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/registry.json': {
      id: '/r/registry.json'
      path: '/r/registry.json'
      fullPath: '/r/registry.json'
      preLoaderRoute: typeof RRegistryDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$name.json': {
      id: '/r/$name.json'
      path: '/r/$name.json'
      fullPath: '/r/$name.json'
      preLoaderRoute: typeof RNameDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  OverviewRoute: OverviewRoute,
  PaymentRoute: PaymentRoute,
  RNameDotjsonRoute: RNameDotjsonRoute,
  RRegistryDotjsonRoute: RRegistryDotjsonRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
