app = "caddy-proxy"
primary_region = "lhr"

[deploy]
    strategy = "immediate"

[http_service]
    internal_port = 80
    force_https = true
    auto_stop_machines = true
    auto_start_machines = true
    min_machines_running = 1

[[services]]
    protocol = "tcp"
    internal_port = 443
    [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

[[vm]]
    memory = "256MB"
    cpu_kind = "shared"
    cpus = 1
