ALTER TABLE `payments` ADD `amount` real NOT NULL;
ALTER TABLE `payments` ADD `callback_url` text NOT NULL;
ALTER TABLE `payments` ADD `metadata` text;
ALTER TABLE `payments` ADD `created_at` integer;
ALTER TABLE `payments` ADD `updated_at` integer;
CREATE INDEX `reference_idx` ON `payments` (`reference`);
ALTER TABLE `transactions` ADD `payment_id` text REFERENCES payments(id);
ALTER TABLE `transactions` ADD `ramp_id` text REFERENCES ramps(id);
CREATE INDEX `transactions_paymentId_idx` ON `transactions` (`payment_id`);
CREATE INDEX `transactions_rampId_idx` ON `transactions` (`ramp_id`);
CREATE INDEX `transactions_status_idx` ON `transactions` (`status`);
CREATE INDEX `transactions_network_idx` ON `transactions` (`network`);
ALTER TABLE `transactions` DROP COLUMN `reference`;
ALTER TABLE `transactions` DROP COLUMN `amount`;
ALTER TABLE `transactions` DROP COLUMN `callback_url`;
ALTER TABLE `transactions` DROP COLUMN `merchant_metadata`;